apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: template-api
spec:
  tasks:
    - name: source
      taskRef:
        name: git-clone
    - name: build
      taskRef:
        name: build
      runAfter:
        - runafter-task1  
    - name: security
      taskRef:
        name: security
      runAfter:
        - runafter-task1
    - name: quality
      taskRef:
        name: quality
      runAfter:
        - runafter-task2
        - runafter-task3
    - name: tests
      taskRef:
        name: quality
    - name: deploy
      taskRef:
        name: quality
