apiVersion: tekton.dev/v1beta1  
kind: TaskRun
metadata:
  name: taskrun-security
spec:
  workspaces:
    - name: source
      persistentVolumeClaim:
         claimName: app-source
    - name: sharedlibrary
      persistentVolumeClaim:
         claimName: sharedlibrary

  taskRef:
     name: security
