apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy
spec:
  params:
    - name: appname
      description: Nome da aplicaçao
    - name: appimage
      description: Imagem criada para deploy
  workspaces:
    - name: sharedlibrary
      description: Pasta com os comandos de execucao da pipeline
      readOnly: true                
    - name: source
      description: Pasta com os fontes da aplicacao

  steps:
    - name: deploy
      workingDir: /workspace/source
      image: bitnami/kubectl:latest
      script: |
         [ -f "pipeline/build.sh" ] && sh pipeline/deploy.sh || sh $(workspaces.sharedlibrary.path)/CD/deploy.sh $(params.appimage) $(params.appname)
            