apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector: 
    app: prometheus-server
  type: NodePort  
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30004