{
 "title": "Tekton-Operator",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Workqueue adds total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "tekton_pipelines_controller_workqueue_adds_total",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Workqueue Depth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "tekton_pipelines_controller_workqueue_depth"
    }
   ]
  },
  {
   "title": "Workqueue Queue Latency Seconds",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "tekton_pipelines_controller_workqueue_queue_latency_seconds_count",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pipelines Controller go heap sys",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "tekton_pipelines_controller_go_heap_sys",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pipelines Go Heap Alloc",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 9 },
   "targets": [
    {
     "expr": "tekton_pipelines_controller_go_heap_alloc"
    },
    {
     "expr": "tekton_pipelines_controller_go_heap_idle"
    },
    {
     "expr": "tekton_pipelines_controller_go_heap_in_use"
    },
    {
     "expr": "tekton_pipelines_controller_go_heap_sys"
    }
   ]
  },
  {
   "title": "Pipelines controller client latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 9 },
   "targets": [
    {
     "expr": "tekton_pipelines_controller_client_latency_count"
    }
   ]
  },
  {
   "title": "Go Heap Objects",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "tekton_pipelines_controller_go_heap_objects"
    }
   ]
  }
 ]
}