apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: taskrun-sharedlibrary
spec:
  workspaces:
    - name: output
      persistentVolumeClaim:
         claimName: sharedlibrary
  params:
    - name: revision
      value: main
    - name: url
      value: 'https://github.com/clodonil/tekton-sharedlibrary'
  taskRef:
     name: source