apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: taskrun-source
spec:
  workspaces:
    - name: output
      persistentVolumeClaim:
         claimName: app-source
  params:
    - name: revision
      value: master
    - name: url
      value: 'https://github.com/clodonil/apphello'
  taskRef:
     name: git-clone