apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-exemplo9
spec:
  workspaces:
    - name: pipeline-ws
  tasks:
    - name: build
      workspaces:
        - name: myworkspace
          workspace: pipeline-ws    
      taskRef:
        name: task-exemplo8

