apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipelinerun-bundle-exemplo1-v1
spec:
  pipelineRef:
    name: pipeline-exemplo1-v1
    bundle: docker.io/clodonil/pipeline-exemplo1:v1