apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipelinerun-bundle-exemplo1-run1
spec:
  params  :
    - name: IMAGE
      value: centos
    - name: command
      value:
         - ls
         - -l /
  pipelineRef:
    name: pipeline-exemplo1
    bundle: docker.io/clodonil/pipeline-exemplo1:v2
