apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: quality
spec:
  params:
    - name: appname
      description: Nome da Imagem
    - name: runtime
      description: Runtime da aplicacao           
  workspaces:
    - name: sharedlibrary
      description: Pasta com os comandos de execucao da pipeline
      readOnly: true                
    - name: source
      description: Pasta com os fontes da aplicacao

  stepTemplate:
    workingDir: /workspace/source
    volumeMounts:
      - name: coverage
        mountPath: /coverage

  steps:
    - name: unit-testing
      image: $(params.runtime)
      script: |
        runtime=$(params.runtime)               
        [ -f "pipeline/unittest.sh" ] && sh pipeline/unittest.sh || sh $(workspaces.sharedlibrary.path)/CI/$runtime/tests/unittest.sh 
    - name: sonar
      env:
        - name: SONAR_TOKEN
          valueFrom:
            secretKeyRef:
              name: sonar
              key: SONAR_TOKEN
      image: sonarsource/sonar-scanner-cli
      timeout: 1h
      script: |
        echo $SONAR_TOKEN
        sh $(workspaces.sharedlibrary.path)/CI/$(params.runtime)/sonar/sonar.sh $(params.appname)

  volumes:
    - name: coverage
      emptyDir: {}     