apiVersion: apps/v1
kind: Deployment
metadata:
  name: __app__-deployment
  labels:
    app: __app__
spec:
  replicas: 2
  selector:
    matchLabels:
      app: __app__
  template:
    metadata:
      labels:
        app: __app__
    spec:
      containers:
      - name: __app__
        image: __image__
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: __app__-services
spec:
  type: NodePort
  selector:
    app: __app__
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30002
