---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: tekton-webhook-microservice
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - name: tekton-webhook-microservice
      interceptors:
        - ref:
            name: cel
          params:
          - name: "overlays"
            value:
            - key: runtime
              expression: "body.repository.name.split('-')[1]"    
            - key: appname
              expression: "body.repository.name.split('-')[0]"    
      bindings:
        - ref: tekton-triggerbinding-microservice
      template:
        ref: tekton-triggertemplate-microservice 