apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: gitea-triggerbinding
spec:
  params:
    - name: revision
      value: $(body.repository.default_branch)
    - name: repository
      value: $(body.repository.clone_url)
    - name: runtime
      value: $(extensions.runtime)
    - name: appname
      value: $(extensions.appname)

