---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: tekton-greeter-trigger-template
spec:
  params:
    - name: revision
      description: The git revision
      default: master
    - name: repository
      description: The git repository url
    - name: runtime
      description: Runtime of app
    - name: appname
      description: Aplication name
    - name: version
      description: vesion of application
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: greeter-app-
        labels:
          tekton.dev/pipeline: microservice-api
      spec:
        serviceAccountName: tekton-triggers-example-sa
        pipelineRef:
          name: microservice-api
        params:
          - name: revision
            value: '$(tt.params.revision)'
          - name: url
            value: '$(tt.params.repository)'
          - name: runtime
            value: '$(tt.params.runtime)'
          - name: appname
            value: '$(tt.params.appname)'
          - name: registry
            value: clodonil  
        workspaces:
          - name: sharedlibrary
            persistentVolumeClaim:
               claimName: sharedlibrary
          - name: source
            persistentVolumeClaim:
               claimName: app-source
