---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: gitea-webhook-sharedlibrary
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - name: tekton-webhook-sharedlibrary
      bindings:
        - ref: gitea-triggerbinding-sharedlibrary
      template:
        ref: tekton-triggertemplate-sharedlibrary