apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-source
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---      
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sharedlibrary
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi