---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: tekton-greeter-trigger-template
spec:
  params:
    - name: revision
      description: The git revision
      default: master
    - name: repository
      description: The git repository url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: greeter-app-
        labels:
          tekton.dev/pipeline: microservice-api
      spec:
        serviceAccountName: tekton-triggers-example-sa
        pipelineRef:
          name: microservice-api
        params:
          - name: IMAGE
            value: "clodonil/apphello:1"
          - name: runtime
            value: python
          - name: revision
            value: '$(tt.params.revision)'
          - name: url
            value: '$(tt.params.repository)'
          - name: runtime
            value: 'python'
          - name: appname
            value: 'helloworl'
          - name: registry
            value: clodonil  
        workspaces:
          - name: sharedlibrary
            persistentVolumeClaim:
               claimName: sharedlibrary
          - name: source
            emptyDir: {}     