apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: gitea-triggerbinding
spec:
  params:
    - name: revision
      value: $(body.after)
    - name: repository
      value: $(body.repository.clone_url)
