apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-exemplo11
spec:
  steps:
    - name: step1
      onError: continue
      image: ubuntu      
      script: |
        #!/usr/bin/env bash
        echo "Execunto Step1"
        echo "Finalizado"
        exit 1