apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-exemplo5
spec:
  steps:
    - name: step1
      image: centos
      script: |
        #!/usr/bin/env bash
        curl https://www.google.com > /var/my-volume/site1.txt
      volumeMounts:
        - name: my-volume
          mountPath: /var/my-volume
    - name: step2
      image: ubuntu
      script: |
        #!/usr/bin/env bash
        cat /etc/my-volume/site1.txt
        ls -l /etc/my-volume  
      volumeMounts:
        - name: my-volume
          mountPath: /etc/my-volume
  volumes:
    - name: my-volume
      emptyDir: {}