apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-exemplo8
spec:
  workspaces:
    - name: myworkspace
      description: The folder where we write the message to
      mountPath: /dados
  steps:
    - name: step1
      image: ubuntu
      script: |
        #!/usr/bin/env bash
        touch /dados/file-$(date "+%Y.%m.%d-%H.%M.%S")
        echo "Finalizado"
    - name: step2
      image: ubuntu
      script: |
        #!/usr/bin/env bash
        ls -l /dados
        echo "Finalizado"
