apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task1
spec:
  results:
     - name: saida
  steps:
    - name: step1
      image: ubuntu      
      script: |
        #!/usr/bin/env bash
        echo "Execunto a task1"
        date
        echo "Finalizado"
        echo "passou pela task1" > $(results.saida.path)

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task2
spec:
  params:
    - name: parametro
      default: 'default'
  results:
     - name: saida
  steps:
    - name: step2
      image: ubuntu      
      script: |
        #!/usr/bin/env bash
        echo "Execunto a task2"
        date
        echo "Finalizado"
        echo "$(params.parametro)"
        echo "$(params.parametro) Task2" > $(results.saida.path)
        if [ "$(params.parametro" == "erro" ]; then
           exit 1
        if
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task3
spec:
  params:
    - name: parametro
      default: 'default'
  results:
     - name: saida
  steps:
    - name: step1
      image: ubuntu      
      script: |
        #!/usr/bin/env bash
        echo "Execunto task3"
        date
        echo "Finalizado"
        echo "$(params.parametro)"
        echo "$(params.parametro) Task3" > $(results.saida.path)

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task4
spec:
  params:
    - name: parametro
      default: 'default'
  steps:
    - name: step1
      image: ubuntu      
      script: |
        #!/usr/bin/env bash
        echo "Execunto task4"
        date
        echo "Finalizado"
        echo "$(params.parametro)"

