apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-exemplo6
spec:
  params:
     - name: image
       type: string
  steps:
    - name: test-carga
      image: loadimpact/k6
      script: |
        cat <<EOF >>test.js
        import http from 'k6/http';
        import { sleep } from 'k6';
        export default function () {
            http.get('http://localhost');
            sleep(1);
        }
        EOF
        k6 run test.js 
  sidecars:
    - image: $(params.image)
      name: server