apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: task-exemplo12
spec:
  params:
     - name: step1_status_code
       type: string
  steps:
    - name: step1
      onError: continue
      image: ubuntu      
      script: |
        #!/usr/bin/env bash
        echo "Execunto Step1"
        echo "Finalizado"
        exit $(params.step1_status_code)
    - name: step2
      image: ubuntu      
      script: |
        #!/usr/bin/env bash
        echo "Execunto Step2"
        step1="Finalizou com sucesso"
        result_step1=`cat $(steps.step-step1.exitCode.path)`
        if [ ${result_step1} -ne 0 ]; then step1="Finalizou com falha"; fi
        echo "O step 1 finalizou com $step1"
        echo "Finalizado"        