apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      name: gitea
      labels:
        app: gitea
    spec:
      containers:
        - image: gitea/gitea:1.15.7
          imagePullPolicy: Always
          name: gitea
          env:
            - name: ALLOWED_HOST_LIST
              value: "*"
            - name: I_UNDERSTAND_I_AM_USING_AN_UNSTABLE_VERSION
              value: "true"
            - name: I_AGREE_TO_FIX_BUGS_AND_NOT_FILE_BUGS
              value: "true"
          ports:
            # SSH
            - containerPort: 22
              protocol: TCP
            # Web
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              cpu: 1
              memory: 1G
          volumeMounts:
          - mountPath: /var/tmp/gitea
            name: db-volume
      volumes:
      - name: db-volume
        hostPath:
          # directory location on host
          path: /var/tmp/gitea