apiVersion: v1
kind: Service
metadata:
  name: gitea
spec:
  type: NodePort
  ports:
    - name: web
      port: 30005
      protocol: TCP
      targetPort: 3000
      nodePort: 30005
    - name: ssh
      port: 30006
      protocol: TCP
      targetPort: 22
      nodePort: 30006
  selector:
    app: gitea
