kind: Secret
apiVersion: v1
metadata:
  name: webhook-secret
stringData:
  url: https://discordapp.com/api/webhooks/961401174764957796/HeCuM9WMWYCri2cxYm8XbuCxE6DBwVN9EKBCkoAUz2PWrvQbH8Bb-tFj4sCnpuisiF1c